BUG: Only copy the ITK .clang-format file if the file does not exist
To address:

   Ref 'HEAD' was rewritten
   error: Untracked working tree file '.clang-format' would be overwritten by merge.